#!/usr/bin/env node
// compress-pdf.mjs
//
// Shrinks a PDF under a size cap (e.g. eFRRO's 1 MB limit) with CAREFUL,
// content-aware compression — using only local libraries (pdf-lib + sharp +
// pako), no ghostscript/qpdf.
//
// DESIGN: we NEVER rebuild pages. We load the document once and only ever swap
// individual image XObjects' stream bytes IN PLACE. Every page, its content
// stream, its selectable TEXT and all other objects are left exactly as they
// were — "replace the pictures, touch nothing else". This keeps the file
// structurally identical to the original (important: some strict server-side
// parsers, e.g. eFRRO's, reject PDFs that have been rebuilt/reordered), and it
// means TEXT IS NEVER TURNED INTO AN IMAGE.
//
// The output is always saved with useObjectStreams:false → a classic PDF with a
// plain cross-reference TABLE (no ObjStm / XRef-stream), the most universally
// compatible layout. Images are re-encoded as BASELINE (non-progressive) JPEG,
// which PDF's DCTDecode reliably supports (progressive JPEGs can fail to open).
//
// RESOLUTION CAP: any embedded image whose longest side exceeds
// MAX_LONGEST_SIDE (1280 px) is DOWNSAMPLED to that ceiling. This was the real
// cause of eFRRO refusing to render an uploaded PDF: a visa scan at 1729×2393
// showed a blank preview, while the accepted passport scans were 1280 px on
// their long side. A file can be under the byte cap yet still have an
// over-resolution image, so we always run the image pass when any image is
// too large — even if de-duplication alone already fit the size limit.
//
// Two steps, applied in order:
//
//   0. De-duplicate identical streams (LOSSLESS). Some generators (mPDF tickets)
//      embed the same subset font dozens of times; we keep one copy and repoint
//      references. Often this alone gets a text-heavy PDF under the cap.
//
//   1. Recompress the large image streams IN PLACE, WATER-LEVELED by file
//      weight: at each step the currently HEAVIEST image is re-encoded one
//      quality step lower (99→…→80, never below 80%), always from its ORIGINAL
//      pixels (so stepping down never compounds JPEG loss). The biggest image is
//      compressed first; as it shrinks to match the next, they compress together
//      and every image ends up ~equal in bytes. Images that can't be swapped
//      safely (transparency masks, exotic codecs, palettes) are left untouched.
//      Encoding uses sharp (the @napi-rs/canvas encoder is broken — it ignores
//      the quality argument and outputs ~8 KB mush).
//
// Usage:
//   node compress-pdf.mjs <input.pdf> [output.pdf] [maxMB]     (maxMB default 1.0)
//     If output.pdf is omitted, writes "<input>-COMPRESSED.pdf" next to the input.
//
// Requires: pdf-lib, sharp, pako  (npm dependencies).

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { PDFDocument, PDFRawStream, PDFRef, PDFDict, PDFArray } from 'pdf-lib';
// sharp is the only reliable image encoder available here (see pdf-image-tools).
import {
  listImageStreams,
  decodeImageSource,
  writeJpegToImageStream,
} from './pdf-image-tools.mjs';

// ---- args -----------------------------------------------------------------

const INPUT = process.argv[2];
if (!INPUT) {
  console.error(
    'Usage: node compress-pdf.mjs <input.pdf> [output.pdf] [maxMB]'
  );
  console.error(
    '  If output.pdf is omitted, writes "<input>-COMPRESSED.pdf" next to the input.'
  );
  process.exit(1);
}
// If no explicit output, mark the compressed copy with a -COMPRESSED suffix so
// the untouched original is never overwritten.
// The second argument is the size cap only when it is nothing but a number;
// an output file named "2024-visa.pdf" is a file name.
const isNumber = (value) => /^\d+(?:\.\d+)?$/.test(value ?? '');
const OUTPUT =
  process.argv[3] && !isNumber(process.argv[3])
    ? process.argv[3]
    : `${INPUT.replace(/\.pdf$/i, '')}-COMPRESSED.pdf`;
const MAX_BYTES =
  (parseFloat(
    process.argv[4] || (isNumber(process.argv[3]) ? process.argv[3] : '')
  ) || 1.0) *
  1024 *
  1024;

// Any image whose longest side exceeds this is downsampled to it. 1280 px is
// the long side of the passport scans eFRRO accepted; larger images (e.g. a
// 1729×2393 visa) render as a blank preview on the portal.
const MAX_LONGEST_SIDE = 1280;

let srcBytes = new Uint8Array(fs.readFileSync(INPUT));

// ---- step 0: de-duplicate identical streams (LOSSLESS) ---------------------
//
// PDFs generated by some tools (e.g. mPDF e-tickets) embed the SAME subset font
// stream dozens of times — one copy per page/fragment. These are byte-identical,
// so we can keep one copy and repoint every reference at it. This drops a lot of
// weight with ZERO change to the visible document or its selectable text.

async function deduplicateStreams(bytes) {
  const doc = await PDFDocument.load(bytes);
  const ctx = doc.context;

  // Group indirect raw streams by content hash (skip tiny ones — not worth it).
  const byHash = new Map();
  for (const [ref, obj] of ctx.enumerateIndirectObjects()) {
    if (
      obj instanceof PDFRawStream &&
      obj.contents &&
      obj.contents.length >= 200
    ) {
      const hash = crypto
        .createHash('sha1')
        .update(Buffer.from(obj.contents))
        .digest('hex');
      if (!byHash.has(hash)) {
        byHash.set(hash, []);
      }
      byHash.get(hash).push(ref);
    }
  }

  // Map each duplicate ref to the one canonical ref we keep.
  const canonical = new Map(); // tag -> keepRef
  for (const refs of byHash.values()) {
    if (refs.length < 2) {
      continue;
    }
    for (let i = 1; i < refs.length; i++) {
      canonical.set(refs[i].tag, refs[0]);
    }
  }
  if (canonical.size === 0) {
    return { bytes, removed: 0 };
  }

  // Repoint every reference that targets a duplicate to the canonical ref.
  const remap = (r) =>
    r instanceof PDFRef && canonical.has(r.tag) ? canonical.get(r.tag) : r;
  const walk = (obj) => {
    if (obj instanceof PDFArray) {
      for (let i = 0; i < obj.size(); i++) {
        const v = obj.get(i);
        if (v instanceof PDFRef) {
          const nr = remap(v);
          if (nr !== v) {
            obj.set(i, nr);
          }
        } else {
          walk(v);
        }
      }
    } else if (obj instanceof PDFDict) {
      for (const [k, v] of obj.entries()) {
        if (v instanceof PDFRef) {
          const nr = remap(v);
          if (nr !== v) {
            obj.set(k, nr);
          }
        } else {
          walk(v);
        }
      }
    } else if (obj instanceof PDFRawStream) {
      walk(obj.dict);
    }
  };
  for (const [, obj] of ctx.enumerateIndirectObjects()) {
    walk(obj);
  }

  // Delete the now-orphaned duplicate objects.
  for (const tag of canonical.keys()) {
    const [num, gen] = tag.split(' ').map(Number);
    ctx.delete(PDFRef.of(num, gen));
  }
  // useObjectStreams:false → a classic PDF with a plain cross-reference TABLE
  // (no ObjStm / XRef-stream). This is the most universally compatible layout;
  // stricter server-side parsers (e.g. eFRRO's) can fail to open PDFs that use
  // compressed object streams. It costs a few KB but "opens everywhere" wins.
  const out = await doc.save({ useObjectStreams: false });
  return { bytes: new Uint8Array(out), removed: canonical.size };
}

// ---- drive -----------------------------------------------------------------

const originalSize = srcBytes.length;

// Step 0: lossless stream de-duplication (fonts etc.). Always safe; do it first.
const dedup = await deduplicateStreams(srcBytes);
if (dedup.removed > 0) {
  srcBytes = dedup.bytes;
  console.log(
    `Lossless: removed ${dedup.removed} duplicate stream(s) → ${(originalSize / 1048576).toFixed(2)} MB → ${(srcBytes.length / 1048576).toFixed(2)} MB`
  );
}

// Does any embedded image exceed the resolution ceiling? Such an image must be
// downsampled even when the file is already under the byte cap, because eFRRO
// won't render an over-resolution image.
const probeDocument = await PDFDocument.load(srcBytes);
const hasOversizedImage = listImageStreams(probeDocument).some(
  (image) => Math.max(image.width, image.height) > MAX_LONGEST_SIDE
);

// If de-duplication alone already fits AND every image is within the resolution
// ceiling, we're done — no image recompression, full quality and selectable
// text preserved everywhere.
if (srcBytes.length <= MAX_BYTES && !hasOversizedImage) {
  fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
  fs.writeFileSync(OUTPUT, srcBytes);
  console.log(
    `\n✓ Wrote ${OUTPUT}  (${(srcBytes.length / 1048576).toFixed(2)} MB, under the ${(MAX_BYTES / 1048576).toFixed(2)} MB cap — lossless, no image recompression needed)`
  );
  process.exit(0);
}

// Step 1: recompress the document's LARGE image streams IN PLACE. We load the
// document ONCE and mutate only the image XObjects' bytes — every page, its
// content stream, its selectable TEXT and all other objects are left exactly as
// they were. This is the "swap the pictures, touch nothing else" approach: it
// never rebuilds pages, so it can't disturb text or the visa/ticket layout.
//
// WATER-LEVELING by file weight: at each step we take the CURRENTLY HEAVIEST
// image (most bytes in the file) and re-encode ONLY it one quality step lower.
// That pours compression onto the biggest image first; as it shrinks to match
// the next heaviest, they compress together — every image ends up ~equal in
// bytes. Quality steps go 99→…→80 and NEVER below 80%.
const MIN_QUALITY = 0.8;
const QUALITY_LADDER = [
  0.99, 0.98, 0.97, 0.96, 0.95, 0.94, 0.93, 0.92, 0.91, 0.9, 0.88, 0.86, 0.84,
  0.82, 0.8,
];

// Only images bigger than this (in bytes, in the file) are worth recompressing.
const MIN_IMAGE_BYTES = 20 * 1024;

const workingDocument = await PDFDocument.load(srcBytes);
const allImages = listImageStreams(workingDocument);

console.log(
  `${path.basename(INPUT)}: source ${(srcBytes.length / 1048576).toFixed(2)} MB, cap ${(MAX_BYTES / 1048576).toFixed(2)} MB`
);

// Decode each large image to its ORIGINAL pixels ONCE. Every quality attempt
// re-encodes from this source, so stepping down the ladder never compounds JPEG
// loss. Images we can't safely recompress in place are dropped from the pool.
// An image joins the pool if it is either heavy enough to be worth recompressing
// OR over the resolution ceiling (which must be downsampled regardless of its
// current byte weight). decodeImageSource is told the ceiling so every encode
// downsamples over-resolution images to MAX_LONGEST_SIDE first.
const compressibleImages = [];
const decodedSource = new Map(); // image → { encodeJpeg(quality), willResize, targetWidth, targetHeight }
const poolCandidates = allImages
  .filter(
    (candidate) =>
      candidate.byteLength >= MIN_IMAGE_BYTES ||
      Math.max(candidate.width, candidate.height) > MAX_LONGEST_SIDE
  )
  .sort((first, second) => second.byteLength - first.byteLength);
for (const image of poolCandidates) {
  const source = await decodeImageSource(image, MAX_LONGEST_SIDE);
  if (!source) {
    continue;
  }
  decodedSource.set(image, source);
  compressibleImages.push(image);
}

console.log(
  `  ${allImages.length} image(s); ${compressibleImages.length} recompressible (>${MIN_IMAGE_BYTES / 1024}KB or >${MAX_LONGEST_SIDE}px, decodable):`
);
console.log(
  `    ${compressibleImages
    .map((image) => {
      const source = decodedSource.get(image);
      const resizeNote = source.willResize
        ? ` → ${source.targetWidth}×${source.targetHeight}`
        : '';
      return `${image.width}×${image.height}${resizeNote} ${image.filter.replace(/[/[\]]/g, '')} ${(image.byteLength / 1024).toFixed(0)}KB`;
    })
    .join(', ')}`
);

// Each image walks down the quality ladder independently. currentBytes tracks
// its live weight in the file; ladderPosition its current quality step.
const ladderPosition = new Map(compressibleImages.map((image) => [image, 0]));
const currentBytes = new Map(
  compressibleImages.map((image) => [image, image.byteLength])
);

// Encode this image at its current ladder position (from ORIGINAL pixels) and
// write it into the stream in place; record the new byte weight.
async function applyQuality(image) {
  const quality = Math.round(QUALITY_LADDER[ladderPosition.get(image)] * 100);
  const jpegBuffer = await decodedSource.get(image).encodeJpeg(quality);
  await writeJpegToImageStream(image, jpegBuffer);
  currentBytes.set(image, jpegBuffer.length);
}

// Bring every compressible image to the TOP of the ladder first (99%).
for (const image of compressibleImages) {
  await applyQuality(image);
}

async function currentSize() {
  return (await workingDocument.save({ useObjectStreams: false })).length;
}

let stepCount = 0;
let size = await currentSize();
while (size > MAX_BYTES) {
  // Heaviest image that can still go one step lower (not yet at the 80% floor).
  const candidates = compressibleImages
    .filter((image) => ladderPosition.get(image) < QUALITY_LADDER.length - 1)
    .sort(
      (first, second) => currentBytes.get(second) - currentBytes.get(first)
    );
  if (candidates.length === 0) {
    break;
  } // everything at the 80% floor — stop

  const heaviest = candidates[0];
  ladderPosition.set(heaviest, ladderPosition.get(heaviest) + 1);
  await applyQuality(heaviest);
  size = await currentSize();
  stepCount++;
}

// useObjectStreams:false → classic PDF with a plain xref table, maximally
// compatible; eFRRO can reject ObjStm-based PDFs.
const finalBytes = await workingDocument.save({ useObjectStreams: false });
const isUnderCap = finalBytes.length <= MAX_BYTES;

const qualityReport = compressibleImages
  .map((image) => {
    const source = decodedSource.get(image);
    const dimensions = source.willResize
      ? `${source.targetWidth}×${source.targetHeight}`
      : `${image.width}×${image.height}`;
    return `${dimensions}=${(QUALITY_LADDER[ladderPosition.get(image)] * 100).toFixed(0)}% (${(currentBytes.get(image) / 1024).toFixed(0)}KB)`;
  })
  .join(', ');
console.log(`  water-leveled in ${stepCount} step(s): ${qualityReport}`);

fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
fs.writeFileSync(OUTPUT, finalBytes);
if (isUnderCap) {
  console.log(
    `\n✓ Wrote ${OUTPUT}  (${(finalBytes.length / 1048576).toFixed(2)} MB, under the ${(MAX_BYTES / 1048576).toFixed(2)} MB cap — images balanced by weight in place, none below JPEG ${(MIN_QUALITY * 100).toFixed(0)}%, all text kept as text)`
  );
} else {
  console.log(
    `\n⚠ Wrote ${OUTPUT}  (${(finalBytes.length / 1048576).toFixed(2)} MB — still over the ${(MAX_BYTES / 1048576).toFixed(2)} MB cap with every image already at our ${(MIN_QUALITY * 100).toFixed(0)}% floor.`
  );
  console.log(
    `  We do NOT compress below ${(MIN_QUALITY * 100).toFixed(0)}%. To fit, reduce image resolution upstream (in join-passport-visa.mjs) or drop a page.`
  );
}
